# Generated by Django 4.2.3 on 2023-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_rename_tournament_tournamentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmodel",
            name="prise",
            field=models.PositiveIntegerField(),
        ),
    ]
