# Generated by Django 4.2.3 on 2023-07-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("tournaments", "0004_alter_tournamentmodel_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmodel",
            name="to_game",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.gamemodel",
            ),
            preserve_default=False,
        ),
    ]
