# Generated by Django 4.2.3 on 2023-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_tournamentmodel_to_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmodel",
            name="end_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tournamentmodel",
            name="start_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
