# Generated by Django 4.2.3 on 2023-07-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_alter_tournamentmodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmodel",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="tournamentmodel",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
