# Generated by Django 4.2.3 on 2023-07-27 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0007_alter_tournamentmodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmodel",
            name="participants",
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
