# Generated by Django 4.2.3 on 2023-07-12 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewmodel",
            options={"ordering": ["-date_of_publication"]},
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="date_of_publication",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
