# Generated by Django 4.2.3 on 2023-07-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0002_gamemodel_rating"),
        ("game_reviews", "0002_alter_reviewmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewmodel",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="to_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.gamemodel"
            ),
        ),
    ]
