# Generated by Django 4.2.3 on 2023-07-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_reviews", "0004_rategamemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rategamemodel",
            name="rating",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
