# Generated by Django 4.2.3 on 2023-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_reviews", "0005_alter_rategamemodel_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rategamemodel",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default=5,
            ),
        ),
    ]
