# Generated by Django 4.2.3 on 2023-07-07 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=177)),
                ("image", models.URLField()),
                ("genre", models.CharField(max_length=50)),
                ("developer", models.CharField(max_length=50)),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameRatingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10.0)]
                    ),
                ),
                (
                    "from_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.gamemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameCommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "from_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.gamemodel",
                    ),
                ),
            ],
        ),
    ]
