# Generated by Django 4.2.3 on 2023-07-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gamemodel_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemodel",
            name="rating",
        ),
    ]
