# Generated by Django 4.2.3 on 2023-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profilemodel_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="age",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
