# Generated by Django 4.2.3 on 2023-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profilemodel_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="nickname",
            field=models.CharField(default="Empty", max_length=50),
        ),
    ]
