# Generated by Django 4.2.3 on 2023-07-27 08:36

import GameLounge.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profilemodel_nickname"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profilemodel",
            managers=[
                ("objects", GameLounge.accounts.models.CustomUserManager()),
            ],
        ),
    ]
